/-
Authors: Formal Frontier Agents
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import FiniteGroupTateCohomology.Basic
public import Mathlib.RepresentationTheory.Homological.GroupCohomology.FiniteCyclic
public import Mathlib.RepresentationTheory.Homological.GroupHomology.FiniteCyclic

/-!
# Additive Tate periodicity for finite cyclic groups

For a finite commutative group generated by an explicitly chosen `g`, the two
alternating models in this file are oriented as follows:

* even Tate degrees use `A --N--> A --(g - 1)--> A`;
* odd Tate degrees use `A --(g - 1)--> A --N--> A`.

The comparisons use mathlib's finite-cyclic resolution in positive group
cohomological degrees and negative group-homological degrees.  Degrees `0` and
`-1` are bridged through this library's accepted cokernel/kernel descriptions
of the norm.  The resulting period-two isomorphism is normalized through a
single parity model, so successive shifts telescope.

The pinned mathlib comparisons `groupCohomologyIsoEven`,
`groupCohomologyIsoOdd`, `groupHomologyIsoEven`, and `groupHomologyIsoOdd` are
objectwise isomorphisms and expose no naturality theorem in a representation
morphism.  Consequently this module deliberately provides an objectwise
periodicity API, not a natural isomorphism of coefficient functors.
-/

public section

open CategoryTheory CategoryTheory.Limits

namespace FiniteGroupTateCohomology

universe u

variable {R G : Type u} [CommRing R] [CommGroup G] [Fintype G]

namespace Cyclic

variable (A : Rep.{u} R G) (g : G) (hg : ∀ x, x ∈ Subgroup.zpowers g)

/-- The alternating short-complex homology used in even Tate degrees:
`A --N--> A --(g - 1)--> A`. -/
noncomputable abbrev evenModel : ModuleCat R :=
  (Rep.FiniteCyclicGroup.normHomCompSub A g).homology

/-- The alternating short-complex homology used in odd Tate degrees:
`A --(g - 1)--> A --N--> A`. -/
noncomputable abbrev oddModel : ModuleCat R :=
  (Rep.FiniteCyclicGroup.subCompNormHom A g).homology

/-- The endomorphism `g - 1` of the underlying coefficient module. -/
noncomputable abbrev generatorSub : ModuleCat.of R A.V ⟶ ModuleCat.of R A.V :=
  ModuleCat.ofHom (Rep.applyAsHom A g - 𝟙 A).hom.toLinearMap

/-- For a chosen generator, the invariant submodule is the kernel of `g - 1`. -/
noncomputable def invariantsIsoKernelGeneratorSub :
    (Rep.invariantsFunctor R G).obj A ≅ kernel (generatorSub A g) :=
  (LinearEquiv.ofEq _ _ (by
      ext x
      simpa [Rep.sub_hom, sub_eq_zero] using
        Representation.mem_invariants_iff_of_forall_mem_zpowers A.ρ g hg x)).toModuleIso ≪≫
    (ModuleCat.kernelIsoKer (generatorSub A g)).symm

private noncomputable def cokernelGeneratorSubIsoCoinvariantsAux :
    cokernel (generatorSub A g) ≅
      ModuleCat.of R (A.V ⧸ Representation.Coinvariants.ker A.ρ) :=
  ModuleCat.cokernelIsoRangeQuotient (generatorSub A g) ≪≫
    (Submodule.quotEquivOfEq _ _ (by
      simpa [generatorSub, Rep.sub_hom, Rep.applyAsHom] using
        Representation.FiniteCyclicGroup.coinvariantsKer_eq_range A.ρ g hg)).toModuleIso.symm

/-- For a chosen generator, the cokernel of `g - 1` is the coinvariant module. -/
noncomputable def cokernelGeneratorSubIsoCoinvariants :
    cokernel (generatorSub A g) ≅ (Rep.coinvariantsFunctor R G).obj A :=
  cokernelGeneratorSubIsoCoinvariantsAux A g hg

omit [Fintype G] in
@[reassoc]
lemma invariantsIsoKernelGeneratorSub_hom_ι :
    (invariantsIsoKernelGeneratorSub A g hg).hom ≫ kernel.ι (generatorSub A g) =
      ModuleCat.ofHom A.ρ.invariants.subtype := by
  dsimp only [invariantsIsoKernelGeneratorSub, Iso.trans_hom, Iso.symm_hom]
  rw [Category.assoc, ModuleCat.kernelIsoKer_inv_kernel_ι]
  ext x
  rfl

set_option backward.isDefEq.respectTransparency false in
@[reassoc]
lemma cokernel_π_cokernelGeneratorSubIsoCoinvariants_hom :
    cokernel.π (generatorSub A g) ≫ (cokernelGeneratorSubIsoCoinvariants A g hg).hom =
      (Rep.coinvariantsMk R G).app A := by
  change cokernel.π (generatorSub A g) ≫
      (cokernelGeneratorSubIsoCoinvariantsAux A g hg).hom =
    ModuleCat.ofHom (Representation.Coinvariants.ker A.ρ).mkQ
  dsimp only [cokernelGeneratorSubIsoCoinvariantsAux, Iso.trans_hom, Iso.symm_hom]
  rw [← Category.assoc,
    ModuleCat.cokernel_π_cokernelIsoRangeQuotient_hom]
  ext x
  let h : Representation.Coinvariants.ker A.ρ =
      LinearMap.range (generatorSub A g).hom := by
    simpa [generatorSub, Rep.sub_hom, Rep.applyAsHom] using
      Representation.FiniteCyclicGroup.coinvariantsKer_eq_range A.ρ g hg
  change (Submodule.quotEquivOfEq _ _ h).symm (Submodule.Quotient.mk x) =
    Submodule.Quotient.mk x
  apply (Submodule.quotEquivOfEq _ _ h).injective
  simp

private lemma kernelLift_eq_coinvariants_norm_invariantsIso :
    kernel.lift (generatorSub A g)
        (ModuleCat.ofHom A.norm.hom.toLinearMap)
          (by ext; simp [generatorSub, Rep.sub_hom, Rep.applyAsHom, Rep.norm]) =
      (Rep.coinvariantsMk R G).app A ≫ normFromCoinvariants A ≫
        (invariantsIsoKernelGeneratorSub A g hg).hom := by
  apply (cancel_mono (kernel.ι (generatorSub A g))).1
  rw [kernel.lift_ι]
  simp only [Category.assoc, invariantsIsoKernelGeneratorSub_hom_ι]
  exact coinvariantsMk_normFromCoinvariants_inclusion A

private lemma cokernelDesc_eq_coinvariantsIso_norm_inclusion :
    cokernel.desc (generatorSub A g) (ModuleCat.ofHom A.norm.hom.toLinearMap)
        (by ext; simp [generatorSub, Rep.sub_hom, Rep.applyAsHom, Rep.norm]) =
      (cokernelGeneratorSubIsoCoinvariants A g hg).hom ≫
        normFromCoinvariants A ≫ ModuleCat.ofHom A.ρ.invariants.subtype := by
  apply (cancel_epi (cokernel.π (generatorSub A g))).1
  rw [cokernel.π_desc,
    cokernel_π_cokernelGeneratorSubIsoCoinvariants_hom_assoc]
  exact coinvariantsMk_normFromCoinvariants_inclusion A

/-- The even alternating model is canonically the cokernel of the norm from
coinvariants to invariants. -/
noncomputable def evenModelIsoCokernelNorm :
    evenModel A g ≅ cokernel (normFromCoinvariants A) :=
  (Rep.FiniteCyclicGroup.normHomCompSub A g).homologyIsoCokernelLift ≪≫
    cokernelIsoOfEq (kernelLift_eq_coinvariants_norm_invariantsIso A g hg) ≪≫
    cokernelEpiComp ((Rep.coinvariantsMk R G).app A)
      (normFromCoinvariants A ≫ (invariantsIsoKernelGeneratorSub A g hg).hom) ≪≫
    cokernelCompIsIso (normFromCoinvariants A)
      (invariantsIsoKernelGeneratorSub A g hg).hom

/-- The odd alternating model is canonically the kernel of the norm from
coinvariants to invariants. -/
noncomputable def oddModelIsoKernelNorm :
    oddModel A g ≅ kernel (normFromCoinvariants A) :=
  by
    letI : Mono (ModuleCat.ofHom A.ρ.invariants.subtype) :=
      (ModuleCat.mono_iff_injective _).2 Subtype.val_injective
    exact (Rep.FiniteCyclicGroup.subCompNormHom A g).homologyIsoKernelDesc ≪≫
      kernelIsoOfEq (cokernelDesc_eq_coinvariantsIso_norm_inclusion A g hg) ≪≫
      kernelIsIsoComp (cokernelGeneratorSubIsoCoinvariants A g hg).hom
        (normFromCoinvariants A ≫ ModuleCat.ofHom A.ρ.invariants.subtype) ≪≫
      kernelCompMono (normFromCoinvariants A) (ModuleCat.ofHom A.ρ.invariants.subtype)

private noncomputable def tateIsoEvenZero :
    tateCohomology A 0 ≅ evenModel A g :=
  tateCohomologyZeroIsoCokernelNorm A ≪≫
    (evenModelIsoCokernelNorm (R := R) (G := G) A g hg).symm

private noncomputable def tateIsoOddNegOne :
    tateCohomology A (-1) ≅ oddModel A g :=
  tateCohomologyNegOneIsoKernelNorm A ≪≫
    (oddModelIsoKernelNorm (R := R) (G := G) A g hg).symm

private noncomputable def tateIsoEvenPositive (i : ℕ) [NeZero i] (hi : Even i) :
    tateCohomology A (i : ℤ) ≅ evenModel A g :=
  (TateCohomology.isoGroupCohomology (R := R) (G := G) i).app A ≪≫
    Rep.FiniteCyclicGroup.groupCohomologyIsoEven A g hg i hi

private noncomputable def tateIsoOddPositive (i : ℕ) (hi : Odd i) :
    tateCohomology A (i : ℤ) ≅ oddModel A g := by
  letI : NeZero i := ⟨by
    intro h
    subst i
    exact Nat.not_odd_zero hi⟩
  exact (TateCohomology.isoGroupCohomology (R := R) (G := G) i).app A ≪≫
      Rep.FiniteCyclicGroup.groupCohomologyIsoOdd A g hg i hi

private noncomputable def tateIsoEvenNegative (i : ℕ) [NeZero i] (hi : Odd i) :
    tateCohomology A (-(i + 1 : ℤ)) ≅ evenModel A g := by
  let _ := Classical.decEq G
  exact (TateCohomology.isoGroupHomology (R := R) (G := G)
      (-(i + 1 : ℤ)) i rfl).app A ≪≫
    Rep.FiniteCyclicGroup.groupHomologyIsoOdd A g hg i hi

private noncomputable def tateIsoOddNegative (i : ℕ) [NeZero i] (hi : Even i) :
    tateCohomology A (-(i + 1 : ℤ)) ≅ oddModel A g := by
  let _ := Classical.decEq G
  exact (TateCohomology.isoGroupHomology (R := R) (G := G)
      (-(i + 1 : ℤ)) i rfl).app A ≪≫
    Rep.FiniteCyclicGroup.groupHomologyIsoEven A g hg i hi

/-- Tate cohomology in every even integer degree, compared coherently with
`A --N--> A --(g - 1)--> A`. -/
noncomputable def tateCohomologyIsoEven (n : ℤ) (hn : Even n) :
    tateCohomology A n ≅ evenModel A g := by
  cases n with
  | ofNat i =>
      cases i with
      | zero =>
          exact tateIsoEvenZero (R := R) (G := G) A g hg
      | succ i =>
          have hi_even : Even (i + 1) := (Int.even_coe_nat (i + 1)).mp hn
          letI : NeZero (i + 1) := ⟨Nat.succ_ne_zero i⟩
          exact tateIsoEvenPositive A g hg (i + 1) hi_even
  | negSucc i =>
      change Even (-(i + 1 : ℤ)) at hn
      have hi_succ_even : Even (i + 1) :=
        (Int.even_coe_nat (i + 1)).mp (even_neg.mp hn)
      have hi_odd : Odd i :=
        Nat.not_even_iff_odd.mp (Nat.even_add_one.mp hi_succ_even)
      letI : NeZero i := ⟨by
        intro h
        subst i
        exact Nat.not_odd_zero hi_odd⟩
      exact tateIsoEvenNegative A g hg i hi_odd

/-- Tate cohomology in every odd integer degree, compared coherently with
`A --(g - 1)--> A --N--> A`. -/
noncomputable def tateCohomologyIsoOdd (n : ℤ) (hn : Odd n) :
    tateCohomology A n ≅ oddModel A g := by
  cases n with
  | ofNat i =>
      cases i with
      | zero => exact False.elim (Int.not_odd_zero hn)
      | succ i =>
          have hi_odd : Odd (i + 1) := (Int.odd_coe_nat (i + 1)).mp hn
          exact tateIsoOddPositive A g hg (i + 1) hi_odd
  | negSucc i =>
      cases i with
      | zero =>
          exact tateIsoOddNegOne (R := R) (G := G) A g hg
      | succ i =>
          change Odd (-((i + 1) + 1 : ℤ)) at hn
          have hi_succ_odd : Odd ((i + 1) + 1) :=
            (Int.odd_coe_nat ((i + 1) + 1)).mp (odd_neg.mp hn)
          have hi_even : Even (i + 1) :=
            Nat.not_odd_iff_even.mp (Nat.odd_add_one.mp hi_succ_odd)
          letI : NeZero (i + 1) := ⟨Nat.succ_ne_zero i⟩
          exact tateIsoOddNegative A g hg (i + 1) hi_even

/-- At degree `0`, the even comparison is exactly the accepted cokernel-of-norm
comparison followed by the inverse model identification. -/
lemma tateCohomologyIsoEven_zero :
    tateCohomologyIsoEven A g hg 0 (by simp) =
      tateCohomologyZeroIsoCokernelNorm A ≪≫
        (evenModelIsoCokernelNorm (R := R) (G := G) A g hg).symm := by
  rfl

/-- At degree `-1`, the odd comparison is exactly the accepted kernel-of-norm
comparison followed by the inverse model identification. -/
lemma tateCohomologyIsoOdd_negOne :
    tateCohomologyIsoOdd A g hg (-1) (by simp) =
      tateCohomologyNegOneIsoKernelNorm A ≪≫
        (oddModelIsoKernelNorm (R := R) (G := G) A g hg).symm := by
  rfl

/-- The normalized isomorphism between any two Tate degrees of the same parity.
It is defined by mapping both degrees to their common alternating model. -/
noncomputable def tateCohomologyParityIso (n m : ℤ) (h : Even n ↔ Even m) :
    tateCohomology A n ≅ tateCohomology A m := by
  by_cases hn : Even n
  · exact tateCohomologyIsoEven A g hg n hn ≪≫
      (tateCohomologyIsoEven A g hg m (h.mp hn)).symm
  · have hn' : Odd n := Int.not_even_iff_odd.mp hn
    have hm : ¬Even m := fun hm ↦ hn (h.mpr hm)
    exact tateCohomologyIsoOdd A g hg n hn' ≪≫
      (tateCohomologyIsoOdd A g hg m (Int.not_even_iff_odd.mp hm)).symm

/-- The normalized same-parity isomorphism at one degree is the identity. -/
@[simp]
lemma tateCohomologyParityIso_self (n : ℤ) :
    tateCohomologyParityIso A g hg n n Iff.rfl = Iso.refl _ := by
  by_cases hn : Even n <;> simp [tateCohomologyParityIso, hn]

/-- Normalized same-parity comparisons invert by reversing their endpoints. -/
lemma tateCohomologyParityIso_symm (n m : ℤ) (h : Even n ↔ Even m) :
    (tateCohomologyParityIso A g hg n m h).symm =
      tateCohomologyParityIso A g hg m n h.symm := by
  by_cases hn : Even n
  · have hm := h.mp hn
    simp [tateCohomologyParityIso, hn, hm]
  · have hm : ¬Even m := fun hm ↦ hn (h.mpr hm)
    simp [tateCohomologyParityIso, hn, hm]

/-- Normalized same-parity comparisons telescope through an intermediate
degree. -/
lemma tateCohomologyParityIso_trans (n m l : ℤ)
    (hnm : Even n ↔ Even m) (hml : Even m ↔ Even l) :
    tateCohomologyParityIso A g hg n m hnm ≪≫
        tateCohomologyParityIso A g hg m l hml =
      tateCohomologyParityIso A g hg n l (hnm.trans hml) := by
  by_cases hn : Even n
  · have hm := hnm.mp hn
    have hl := hml.mp hm
    simp [tateCohomologyParityIso, hn, hm]
  · have hm : ¬Even m := fun hm ↦ hn (hnm.mpr hm)
    have hl : ¬Even l := fun hl ↦ hm (hml.mpr hl)
    simp [tateCohomologyParityIso, hn, hm]

/-- Additive period-two Tate cohomology for a finite cyclic group with chosen
generator. -/
noncomputable def tateCohomologyPeriodicity (n : ℤ) :
    tateCohomology A n ≅ tateCohomology A (n + 2) :=
  tateCohomologyParityIso A g hg n (n + 2) even_add_two.symm

/-- Two consecutive period-two shifts are the normalized same-parity
comparison across four degrees; the intermediate model cancels. -/
lemma tateCohomologyPeriodicity_trans (n : ℤ) :
    tateCohomologyPeriodicity A g hg n ≪≫
        tateCohomologyPeriodicity A g hg (n + 2) =
      tateCohomologyParityIso A g hg n ((n + 2) + 2)
        (even_add_two.symm.trans even_add_two.symm) :=
  tateCohomologyParityIso_trans A g hg _ _ _ _ _

end Cyclic

end FiniteGroupTateCohomology
